// ─────────────────────────────────────────────────────────────────────────────
// lib/ai/chat-config.ts — the HallNect Assistant's fixed, client-safe settings.
//
// Pure data, no I/O and no secrets, so the chat UI and the /api/chat route
// read the SAME limits, quick actions and route allowlist. Keep it that way:
// anything that needs the database or an API key lives in lib/ai/*.server.ts.
//
// ONE PLACE TO EDIT. The welcome text, the quick actions and the action routes
// are the parts an admin screen would manage later; they are isolated here so
// that screen can replace this module's values without touching the UI.
// ─────────────────────────────────────────────────────────────────────────────

export const CHAT_API_PATH = "/api/chat";

export const ASSISTANT_NAME = "HallNect Assistant";
export const ASSISTANT_TAGLINE = "Your smart venue booking assistant";

export const WELCOME_MESSAGE =
  "Hi! 👋 I'm the HallNect Assistant.\n" +
  "I can help you find halls, understand bookings, explore HallNect features, or answer your questions.";

/** Characters in one message typed by the user. Enforced on the server too. */
export const MAX_INPUT_CHARS = 1000;
/** Messages of history sent per request; older turns are dropped (server re-enforces). */
export const MAX_HISTORY_MESSAGES = 16;

export type QuickAction = { id: string; label: string; prompt: string };

export const QUICK_ACTIONS: readonly QuickAction[] = [
  { id: "find_hall",      label: "🏛️ Find a Hall",         prompt: "Help me find a wedding hall." },
  { id: "availability",   label: "📅 Check Availability",  prompt: "How can I check if a hall is available on my date?" },
  { id: "pricing",        label: "💰 Pricing & Plans",      prompt: "What does it cost to book a hall on HallNect, and what are the plans for hall owners?" },
  { id: "how_booking",    label: "📖 How Booking Works",    prompt: "How does booking a hall on HallNect work?" },
  { id: "owner",          label: "👤 I'm a Hall Owner",     prompt: "I own a hall. How do I list it on HallNect?" },
  { id: "support",        label: "❓ Help & Support",       prompt: "I need help. How do I contact HallNect support?" },
] as const;

/**
 * Buttons the assistant may attach to a reply. The model can only name a KEY;
 * the href comes from here, so it can never produce a route that does not
 * exist. Every href below is a real page in app/.
 */
export const CHAT_ACTION_ROUTES = {
  browse_halls:       { label: "Browse Halls",            href: "/halls" },
  login:              { label: "Login",                   href: "/login" },
  register:           { label: "Register",                href: "/signup" },
  become_owner:       { label: "Become a Hall Owner",     href: "/owner/register" },
  owner_dashboard:    { label: "Open Owner Dashboard",    href: "/owner/dashboard" },
  owner_premium:      { label: "Owner Plans",             href: "/owner/premium" },
  pricing:            { label: "View Plans",              href: "/premium" },
  my_bookings:        { label: "My Bookings",             href: "/customer/bookings" },
  my_enquiries:       { label: "My Enquiries",            href: "/customer/enquiries" },
  contact_support:    { label: "Contact Support",         href: "/contact" },
  refund_policy:      { label: "Refund Policy",           href: "/refund-policy" },
  cancellation_policy:{ label: "Cancellation Policy",     href: "/cancellation-policy" },
  verify_phone:       { label: "Verify Mobile Number",    href: "/verify-phone" },
} as const;

export type ChatActionKey = keyof typeof CHAT_ACTION_ROUTES;
export const CHAT_ACTION_KEYS = Object.keys(CHAT_ACTION_ROUTES) as [ChatActionKey, ...ChatActionKey[]];

/** Hall slugs are generated by lib/owner.ts generateSlug: lowercase, digits, hyphens. */
export const HALL_SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** Hrefs a hall card may link to — built from a validated slug only. */
export function hallHref(slug: string): string | null {
  return HALL_SLUG_PATTERN.test(slug) ? `/halls/${slug}` : null;
}

/** Friendly text shown for any failure; technical details stay in server logs. */
export const CHAT_ERROR_MESSAGE = "Sorry, I'm having trouble responding right now. Please try again.";
/** Shown when the AI provider is throttling (the free AI Gateway tier allows only a few requests a minute). */
export const CHAT_BUSY_MESSAGE =
  "HallNect Assistant is busy right now. Please try again in a minute.";
export const CHAT_RATE_LIMIT_MESSAGE =
  "You've sent a lot of messages in a short time. Please wait a little and try again.";

/** Routes where the launcher is not shown at all. */
export const CHAT_HIDDEN_PREFIXES = ["/invoice/"] as const;
